In [ ]:
root = "/content/drive/MyDrive/iNeuron Study/Perceptron Implementation"
import os
os.chdir(root)

In [ ]:
assert root==os.getcwd()

In [2]:
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import matplotlib.colors as ListedColorMAp

In [ ]:
class Perceptron:
  def __init__(self,eta,epochs):
    self.weights = np.random.randn(3)*1e-4
    print(f"Initial weights before training : \n {self.weights}")

    self.eta = eta
    self.epochs = epochs


  def activationFunction(self,inputs,weights):
    z = np.dot(inputs,weights)
    return np.where(z>0, 1, 0)

  def fit(self,X,Y):
    self.X = X
    self.Y = Y

    x_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
    print(f"X with bias : \n {x_with_bias}")

    for epoch in range(self.epochs):
      print("--"*20)
      print(f"For epoch : {epoch}")
      print("--"*20)

      y_hat = self.activationFunction(x_with_bias,self.weights)
      print(f"Predicted Value after forword pass : \n {y_hat}")
      self.error = self.Y-y_hat
      print(f"Error : \n {self.error}")
      self.weights = self.weights + self.eta * np.dot(x_with_bias.T,self.error)
      print(f"Updated weights after epoch : \n {epoch}/{self.epochs} : \n{self.weights}")
      print("**"*20)

  def predict(self,X):
    x_with_bias = np.c_[X, -np.ones((len(X),1))]
    return self.activationFunction(x_with_bias,self.weights)

  def total_loss(self):
    total_loss = np.sum(self.error)
    print(f"TOtal loss : \n {total_loss}")
    return total_loss

In [2]:
def prepare_data(df):
  X = df.drop("y",axis=1)
  y = df['y']
  print(type(X))
  print(type(y))
  return X,y

In [3]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,0,0,1],
}

df = pd.DataFrame(AND)

df

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [ ]:
X,y = prepare_data(df)

ETA = 0.3 # 0 and 1
EPOCHS = 10

model = Perceptron(eta=ETA, epochs=EPOCHS)
model.fit(X, y)

_ = model.total_loss()


Initial weights before training : 
 [-7.80856111e-05 -2.57523496e-05 -4.12882045e-05]
X with bias : 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
----------------------------------------
For epoch : 0
----------------------------------------
Predicted Value after forword pass : 
 [1 1 0 0]
Error : 
 0   -1
1   -1
2    0
3    1
Name: y, dtype: int64
Updated weights after epoch : 
 0/10 : 
[ 2.99921914e-01 -2.57523496e-05  2.99958712e-01]
****************************************
----------------------------------------
For epoch : 1
----------------------------------------
Predicted Value after forword pass : 
 [0 0 0 0]
Error : 
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights after epoch : 
 1/10 : 
[ 5.99921914e-01  2.99974248e-01 -4.12882045e-05]
****************************************
----------------------------------------
For epoch : 2
----------------------------------------
Predicted Value after forword pass : 
 [1 1 1 1]
Error : 
 0   -1
1  